name: Update README with quotes

on:
  push:
      paths:
        - 'QUOTES.txt'  # update when quotes.txt is updated

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read quotes.txt and update README
        run: |
          # read quotes.txt and convert to URI
          QUOTES=$(awk '{
              gsub(/^[ \t]+|[ \t]+$/, "");
              if (length == 0) {
                  if (!p) print "";  # Âè™ÊâìÂç∞‰∏Ä‰∏™Á©∫Ë°å
                  p=1;
              } else {
                  print;
                  p=0;
              }
          }' QUOTES.txt | jq -sRr @uri)
          
          # replace spaces with + and newlines with ;
          NEW_LINES=$(echo "$QUOTES" | sed 's/ /+/g' | tr '\n' ';')

          # replace lines in README
          if grep -q "lines=" README.md; then
            sed -i "s|lines=.*|lines=${NEW_LINES})|g" README.md
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "üîÑ Auto update Typing SVG in README"
          git push
